# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: credential-provider
nodes:
- role: control-plane
  image: kind-credential-provider-node
  extraMounts:
  - hostPath: ./kind-kubelet-credential-providers.yaml
    containerPath: /etc/kubernetes/kubelet-credential-providers.yaml
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: "KubeletServiceAccountTokenForCredentialProviders=true"
        image-credential-provider-config: "/etc/kubernetes/kubelet-credential-providers.yaml"
        image-credential-provider-bin-dir: "/usr/local/bin"
