apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
- name: cgr-credential-provider
  matchImages:
  - "cgr.dev"
  defaultCacheDuration: "1h"
  apiVersion: credentialprovider.kubelet.k8s.io/v1
  tokenAttributes:
    requireServiceAccount: true
    serviceAccountTokenAudience: "https://issuer.enforce.dev"
    requiredServiceAccountAnnotationKeys:
    - "credentials.chainguard.dev/identity"
